In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [2]:
#df_train = pd.read_csv('fashion-mnist_train.csv')
df_test = pd.read_csv('fashion-mnist_test.csv')
df_test

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0         0       0       0       0       0       0       0       0       9   
1         1       0       0       0       0       0       0       0       0   
2         2       0       0       0       0       0       0      14      53   
3         2       0       0       0       0       0       0       0       0   
4         3       0       0       0       0       0       0       0       0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995      0       0       0       0       0       0       0       0       0   
9996      6       0       0       0       0       0       0       0       0   
9997      8       0       0       0       0       0       0       0       0   
9998      8       0       1       3       0       0       0       0       0   
9999      1       0       0       0       0       0       0       0     140   

      pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          8  ...       103        87        56         0         0         0   
1          0  ...        34         0         0         0         0         0   
2         99  ...         0         0         0         0        63        53   
3          0  ...       137       126       140         0       133       224   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
9995       0  ...        32        23        14        20         0         0   
9996       0  ...         0         0         0         2        52        23   
9997       0  ...       175       172       172       182       199       222   
9998       0  ...         0         0         0         0         0         1   
9999     119  ...       111        95        75        44         1         0   

      pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0  
1            0         0         0         0  
2           31         0         0         0  
3          222        56         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
9995         1         0         0         0  
9996        28         0         0         0  
9997        42         0         1         0  
9998         0         0         0         0  
9999         0         0         0         0  

[10000 rows x 785 columns]

In [3]:
#X_train = df_train.drop('label', axis=1)
#y_train = df_train['label']

#X_train = np.array(X_train[:800])
#y_train = np.array(y_train[:800])

#X_test = df_test.drop('label', axis=1)
#y_test = df_test['label']

#X_test = np.array(X_test[:200])
#y_test = np.array(y_test[:200])

X = df_test.drop('label', axis=1)
y = df_test['label']

X = np.array(X[:2000])
y = np.array(y[:2000])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0)

BAGGING CLASSIFIER

In [14]:
model = BaggingClassifier(base_estimator=KNeighborsClassifier(n_neighbors=2), n_estimators=80, random_state=0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("precision score: " + str(precision_score(y_test, y_pred, average='macro')))
print("recall score: " + str(recall_score(y_test, y_pred, average='macro')))
print(confusion_matrix(y_test, y_pred))

precision score: 0.7967202541862605
recall score: 0.7918905089299826
[[31  1  0  0  1  0  4  0  0  0]
 [ 0 51  1  1  0  0  2  0  0  0]
 [ 1  0 29  0  9  0  9  0  0  0]
 [ 3  3  3 41  3  0  2  0  0  0]
 [ 0  0 11  0 39  0  4  0  0  0]
 [ 0  0  0  0  0 42  0  7  1 10]
 [ 8  1  8  0  3  0 37  0  0  0]
 [ 0  0  0  0  0  0  0 42  0  3]
 [ 4  0  1  1  0  0  0  2 37  0]
 [ 0  0  0  0  0  0  0  1  0 43]]


In [15]:
model = BaggingClassifier(base_estimator=OneVsRestClassifier(SVC()), n_estimators=100, random_state=0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("precision score: " + str(precision_score(y_test, y_pred, average='macro')))
print("recall score: " + str(recall_score(y_test, y_pred, average='macro')))
print(confusion_matrix(y_test, y_pred))

precision score: 0.824133732268941
recall score: 0.8248616858485279
[[32  0  1  1  0  0  2  0  1  0]
 [ 0 51  2  2  0  0  0  0  0  0]
 [ 1  0 33  0 10  0  3  0  1  0]
 [ 3  0  4 46  2  0  0  0  0  0]
 [ 0  0  6  2 42  0  3  0  1  0]
 [ 0  0  0  0  0 53  0  4  0  3]
 [12  0 10  0  2  0 32  0  1  0]
 [ 0  0  0  0  0  3  0 39  0  3]
 [ 0  0  2  1  1  1  0  0 40  0]
 [ 0  0  0  0  0  1  0  1  0 42]]


In [24]:
model = BaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=8), n_estimators=80, random_state=0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("precision score: " + str(precision_score(y_test, y_pred, average='macro')))
print("recall score: " + str(recall_score(y_test, y_pred, average='macro')))
print(confusion_matrix(y_test, y_pred))

precision score: 0.7696571201343433
recall score: 0.7752094079725659
[[29  0  3  1  1  0  2  0  1  0]
 [ 0 49  0  5  0  0  1  0  0  0]
 [ 1  0 34  0 10  0  3  0  0  0]
 [ 3  0  1 45  2  1  3  0  0  0]
 [ 0  0  5  4 35  0 10  0  0  0]
 [ 0  0  0  0  0 48  1  7  2  2]
 [11  0 10  1  7  1 25  0  2  0]
 [ 0  0  0  0  0  3  0 40  0  2]
 [ 0  0  2  1  1  1  0  0 40  0]
 [ 0  0  0  0  0  1  0  3  1 39]]


VOTING CLASSIFIER

In [7]:
neigh = KNeighborsClassifier(n_neighbors=3)
ovr = OneVsRestClassifier(SVC())
dtr = DecisionTreeClassifier(random_state=0)

clf = VotingClassifier(estimators=[('neigh', neigh), ('ovr', ovr), ('dtr', dtr)], voting='hard')
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("precision score: " + str(precision_score(y_test, y_pred, average='macro')))
print("recall score: " + str(recall_score(y_test, y_pred, average='macro')))
print(confusion_matrix(y_test, y_pred))

precision score: 0.8189491923349472
recall score: 0.8114862470125628
[[31  0  1  1  0  0  3  0  1  0]
 [ 0 51  1  2  0  0  1  0  0  0]
 [ 3  0 36  0  5  0  3  0  1  0]
 [ 6  1  4 44  0  0  0  0  0  0]
 [ 0  1 10  1 40  0  2  0  0  0]
 [ 1  0  0  0  0 51  0  3  1  4]
 [13  0 12  0  1  0 31  0  0  0]
 [ 0  0  0  0  0  3  0 39  0  3]
 [ 4  0  1  1  0  0  0  0 39  0]
 [ 0  0  0  0  0  1  0  2  0 41]]


RANDOM FOREST

In [9]:
model = RandomForestClassifier(n_estimators=120, max_depth=8, random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("precision score: " + str(precision_score(y_test, y_pred, average='macro', zero_division=0)))
print("recall score: " + str(recall_score(y_test, y_pred, average='macro')))
print(confusion_matrix(y_test, y_pred))

precision score: 0.7998516631251239
recall score: 0.8056807884439463
[[29  0  1  1  1  0  4  0  1  0]
 [ 0 50  2  3  0  0  0  0  0  0]
 [ 0  0 34  0 10  0  3  0  1  0]
 [ 4  0  3 47  0  0  1  0  0  0]
 [ 0  0  7  2 37  0  8  0  0  0]
 [ 0  0  0  0  0 50  0  4  2  4]
 [ 9  0 10  4  8  0 25  0  1  0]
 [ 0  0  0  0  0  0  0 43  0  2]
 [ 0  0  2  2  0  0  0  0 41  0]
 [ 0  0  0  0  0  0  0  1  0 43]]
