In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [2]:
#df_train = pd.read_csv('fashion-mnist_train.csv')
df_test = pd.read_csv('fashion-mnist_test.csv')
df_test

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0         0       0       0       0       0       0       0       0       9   
1         1       0       0       0       0       0       0       0       0   
2         2       0       0       0       0       0       0      14      53   
3         2       0       0       0       0       0       0       0       0   
4         3       0       0       0       0       0       0       0       0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995      0       0       0       0       0       0       0       0       0   
9996      6       0       0       0       0       0       0       0       0   
9997      8       0       0       0       0       0       0       0       0   
9998      8       0       1       3       0       0       0       0       0   
9999      1       0       0       0       0       0       0       0     140   

      pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          8  ...       103        87        56         0         0         0   
1          0  ...        34         0         0         0         0         0   
2         99  ...         0         0         0         0        63        53   
3          0  ...       137       126       140         0       133       224   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
9995       0  ...        32        23        14        20         0         0   
9996       0  ...         0         0         0         2        52        23   
9997       0  ...       175       172       172       182       199       222   
9998       0  ...         0         0         0         0         0         1   
9999     119  ...       111        95        75        44         1         0   

      pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0  
1            0         0         0         0  
2           31         0         0         0  
3          222        56         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
9995         1         0         0         0  
9996        28         0         0         0  
9997        42         0         1         0  
9998         0         0         0         0  
9999         0         0         0         0  

[10000 rows x 785 columns]

In [3]:
#X_train = df_train.drop('label', axis=1)
#y_train = df_train['label']

#X_train = np.array(X_train[:800])
#y_train = np.array(y_train[:800])

#X_test = df_test.drop('label', axis=1)
#y_test = df_test['label']

#X_test = np.array(X_test[:200])
#y_test = np.array(y_test[:200])

X = df_test.drop('label', axis=1)
y = df_test['label']

X = np.array(X[:500])
y = np.array(y[:500])

#X_train, X_test, y_train, y_test = train_test_split(
    #X, y, random_state=0)

BAGGING CLASSIFIER

In [4]:
model = BaggingClassifier(base_estimator=KNeighborsClassifier(n_neighbors=2), n_estimators=80, random_state=0)

model.fit(X, y)

y_pred = model.predict(X)

print("precision score: " + str(precision_score(y, y_pred, average='macro')))
print("recall score: " + str(recall_score(y, y_pred, average='macro')))
print(confusion_matrix(y, y_pred))

precision score: 0.9599422131750386
recall score: 0.9604489954489954
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 59  0  2  0  2  0  0  0]
 [ 0  0  0 46  0  0  0  0  0  0]
 [ 0  0  0  1 52  0  2  0  0  0]
 [ 0  0  0  0  0 47  0  4  0  1]
 [ 4  0  1  0  2  0 42  0  0  0]
 [ 0  0  0  0  0  0  0 50  0  2]
 [ 0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0  0 47]]


In [5]:
model = BaggingClassifier(base_estimator=OneVsRestClassifier(SVC()), n_estimators=10, random_state=0)

model.fit(X, y)

y_pred = model.predict(X)

print("precision score: " + str(precision_score(y, y_pred, average='macro')))
print("recall score: " + str(recall_score(y, y_pred, average='macro')))
print(confusion_matrix(y, y_pred))

precision score: 0.9281295944879687
recall score: 0.9233362282482442
[[51  0  0  2  0  0  0  0  0  0]
 [ 0 39  1  0  0  0  0  0  0  0]
 [ 2  0 53  0  6  1  1  0  0  0]
 [ 1  0  0 45  0  0  0  0  0  0]
 [ 0  0  1  1 52  0  1  0  0  0]
 [ 0  0  0  0  0 50  0  2  0  0]
 [ 9  0  3  0  2  0 35  0  0  0]
 [ 0  0  0  0  0  1  0 48  0  3]
 [ 0  0  0  0  0  2  0  0 41  0]
 [ 0  0  0  0  0  1  0  0  0 46]]


In [6]:
model = BaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=8), n_estimators=80, random_state=0)

model.fit(X, y)

y_pred = model.predict(X)

print("precision score: " + str(precision_score(y, y_pred, average='macro')))
print("recall score: " + str(recall_score(y, y_pred, average='macro')))
print(confusion_matrix(y, y_pred))

precision score: 1.0
recall score: 1.0
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 63  0  0  0  0  0  0  0]
 [ 0  0  0 46  0  0  0  0  0  0]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0 52  0  0  0  0]
 [ 0  0  0  0  0  0 49  0  0  0]
 [ 0  0  0  0  0  0  0 52  0  0]
 [ 0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0  0 47]]


VOTING CLASSIFIER

In [7]:
neigh = KNeighborsClassifier(n_neighbors=3)
ovr = OneVsRestClassifier(SVC())
dtr = DecisionTreeClassifier(random_state=0)

clf = VotingClassifier(estimators=[('neigh', neigh), ('ovr', ovr), ('dtr', dtr)], voting='hard')
clf = clf.fit(X, y)
y_pred = clf.predict(X)

print("precision score: " + str(precision_score(y, y_pred, average='macro')))
print("recall score: " + str(recall_score(y, y_pred, average='macro')))
print(confusion_matrix(y, y_pred))

precision score: 0.9615978535247842
recall score: 0.9567782855515775
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 39  1  0  0  0  0  0  0  0]
 [ 1  0 61  0  1  0  0  0  0  0]
 [ 1  0  0 45  0  0  0  0  0  0]
 [ 1  0  1  1 51  0  1  0  0  0]
 [ 0  0  0  0  0 50  0  2  0  0]
 [ 7  0  2  0  1  0 39  0  0  0]
 [ 0  0  0  0  0  0  0 50  0  2]
 [ 0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0  0 47]]


RANDOM FOREST

In [8]:
model = RandomForestClassifier(n_estimators=120, max_depth=8, random_state=0)
model.fit(X, y)

y_pred = model.predict(X)

print("precision score: " + str(precision_score(y, y_pred, average='macro', zero_division=0)))
print("recall score: " + str(recall_score(y, y_pred, average='macro')))
print(confusion_matrix(y, y_pred))

precision score: 0.9982142857142857
recall score: 0.9984126984126984
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 62  0  1  0  0  0  0  0]
 [ 0  0  0 46  0  0  0  0  0  0]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0 52  0  0  0  0]
 [ 0  0  0  0  0  0 49  0  0  0]
 [ 0  0  0  0  0  0  0 52  0  0]
 [ 0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0  0 47]]
